### ISSUE TITLE
.eval() does not put torch in no_grad mode

### ISSUE THREAD

**Issue by mctigger** [cpnota/all-example-project#1]
https://github.com/cpnota/all-example-project/blob/eb90aa7bbc8c076239dbfdd301a995c662562093/agent.py#L65

> Choose the best action in the current state using our model predictions.
        Note that every call below uses .eval(), which puts torch in no_grad mode,
        and sometimes changes their behavior.

.eval() does not put torch in no_grad mode, but only allows some modules (such as BatchNorm or Dropout) to go into eval() mode.

**Comment by cpnota** [comment]
`.eval()` here is a `autonomous-learning-library` function, not the underlying torch function. However, in the latest version of the library, the semantics are closer to the torch function. `Approximation.no_grad(*inputs)` makes a forward pass in no_grad mode, `Approximation.eval(*inputs)` both puts the network in eval mode *and* runs the forward pass in no_grad mode. Again, this functionality is implemented by the `all.approximation.Approximation` itself.
